apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: helpy_production
        - name: POSTGRES_PASSWORD
          value: some_secure_pg_password_change_in_production
        - name: POSTGRES_USER
          value: helpy
        - name: SECRET_KEY_BASE
          value: some_secret_key_base_change_in_production
        image: postgres:9.4
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-claim0
          mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
      - name: postgres-claim0
        persistentVolumeClaim:
          claimName: postgres-claim0
