apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "frontend.fullname" . }}
  labels:
    app: {{ template "frontend.name" . }}
    chart: {{ template "frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "frontend.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "frontend.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: dockercred
      containers:
      - image: superpedestrian/caddy:latest
        name: frontend
        terminationMessagePath: "/tmp/my-log"
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /helpy/public
          name: helpy-rails-assets
      restartPolicy: Always
      volumes:
      - name: helpy-rails-assets
        persistentVolumeClaim:
          claimName: helpy-rails-assets
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

