apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - image: vishalrao2911/caddy:latest
        name: frontend
        terminationMessagePath: "/tmp/my-log"
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /helpy/public
          name: helpy-rails-assets
      restartPolicy: Always
      volumes:
      - name: helpy-rails-assets
        persistentVolumeClaim:
          claimName: helpy-rails-assets
status: {}
