apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: helpy
    app: {{ template "helpy.name" . }}
    chart: {{ template "helpy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "helpy.fullname" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ template "helpy.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "helpy.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: dockercred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Values.service.configMapName }}
          ports:
            - name: helpy-http
              containerPort: 8080
              protocol: TCP
          resources: {}
