apiVersion: v1
kind: Service
metadata:
  name: {{ template "helpy.fullname" . }}
  labels:
    app: {{ template "helpy.name" . }}
    chart: {{ template "helpy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "helpy.name" . }}
    release: {{ .Release.Name }}
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: helpy-http
